source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DZAppearanceTools_Example', :exclusive => true do
  pod 'DZAppearanceTools', :path => '../'
end

target 'DZAppearanceTools_Tests', :exclusive => true do
  pod 'DZAppearanceTools', :path => '../'

  pod 'FBSnapshotTestCase'
end
